### ISSUE TITLE
cannot import cccorelib

### ISSUE THREAD

**Issue by BaronWang0130** [Amsterdam-AI-Team/Urban_PointCloud_Processing#31]
![image](https://user-images.githubusercontent.com/88529547/139612233-fa8078bd-4626-4aa1-9c22-c0ccc5ea3fdb.png)
I have already installed the cloudcompare-alpha and cccorelib direct installer on windows. However, it still cannot import cccorelib. Anyone has the same problem?
![image](https://user-images.githubusercontent.com/88529547/139612558-0b2b31e3-e41b-430e-8f37-240387b345bb.png)

**Comment by chrise96** [comment]
Did you follow the "Building as independent wheels" instructions on [this page](https://github.com/tmontaigu/CloudCompare-PythonPlugin/blob/master/docs/building.rst#building-as-indenpendent-wheels)? Also make sure you have pip version >= 
21.1.

**Comment by BaronWang0130** [comment]
Sure. 
Also it cannot import pycc

**Comment by daanbl** [comment]
Unfortunately neither of us has a Windows installation, we have only tested the code on Mac OS and Ubuntu. Since this issue is related to external code, perhaps it is best to ask the author directly: https://github.com/tmontaigu/CloudCompare-PythonPlugin.

**Comment by BaronWang0130** [comment]
I set up for another environment based on ubuntu 20.04 but got another problem and opened the new issue.
