### ISSUE TITLE
Cannot determine Numba type of <class 'shapely.coords.CoordinateSequence'>

### ISSUE THREAD

**Issue by BaronWang0130** [Amsterdam-AI-Team/Urban_PointCloud_Processing#33]
![image](https://user-images.githubusercontent.com/88529547/140467374-477f1d5e-03f8-4e78-9e78-27693a7aa22c.png)
When processing a single file, the erroe is shown above.  By the way, the environment is Ubuntu 20.04 and pycc, cccorelib are built as independent wheels.

**Comment by daanbl** [comment]
Sorry for that, I must have introduced this bug in the previous update. Should be fixed now!
