### ISSUE TITLE
Cannot install "cccorelib"

### ISSUE THREAD

**Issue by Roy2xc** [Amsterdam-AI-Team/Urban_PointCloud_Processing#35]
I tried "pip install cccorelib" but it showed me "ERROR: Could not find a version that satisfies the requirement cccorelib
ERROR: No matching distribution found for cccorelib". 
How can I install this module？ Please give me some hint, Thank you very much~~

**Comment by BaronWang0130** [comment]
built from source code

**Comment by Roy2xc** [comment]
How to built it from source code? I don't know C++...

**Comment by daanbl** [comment]
To install both `pycc` and `cccorelib` please follow the instructions for "building independent wheels" on their respective github page: https://github.com/tmontaigu/CloudCompare-PythonPlugin/blob/master/docs/building.rst

**Comment by Roy2xc** [comment]
> To install both `pycc` and `cccorelib` please follow the instructions for "building independent wheels" on their respective github page: https://github.com/tmontaigu/CloudCompare-PythonPlugin/blob/master/docs/building.rst

Thank you!

**Comment by gsenxu** [comment]
> 要安装两者`pycc`，`cccorelib`请按照各自 github 页面上“构建独立轮子”的说明进行操作：https://github.com/tmontaigu/CloudCompare-PythonPlugin/blob/master/docs/building.rst
error:
![image](https://user-images.githubusercontent.com/70185653/218985965-3dcdad3b-a32e-497c-a7ad-8c88ec357873.png)

**Comment by gsenxu** [comment]
How to solve this problem? I have installed both pycc and cccorelib, but it can not be used.

**Comment by daanbl** [comment]
Hi @gsenxu, are you using Windows? I am aware it is difficult to get those packages working on that operating system, but I have no experience with that myself. It might be best to ask your question directly to the developers of the CloudCompare-PythonPlugin repo.
