### ISSUE TITLE
AttributeError: module 'src.region_growing' has no attribute 'RegionGrowing'

### ISSUE THREAD

**Issue by BaronWang0130** [Amsterdam-AI-Team/Urban_PointCloud_Processing#36]
![image](https://user-images.githubusercontent.com/88529547/140680705-aeac1a3e-42c0-491c-a8b1-dcd22668396c.png)

**Comment by daanbl** [comment]
Thank you for pointing this out. `RegionGrowing` was imported directly at the top so that line should read `region_growing_pcl = RegionGrowing(label=Labels.BUILDING)`.
