### ISSUE TITLE
module 'laspy' has no attribute 'read'

### ISSUE THREAD

**Issue by Roy2xc** [Amsterdam-AI-Team/Urban_PointCloud_Processing#38]
I just run the complete solution and when I run  the block "pipeline.process_file(in_file, out_file)" block, it shows me "module 'laspy' has no attribute 'read'".

What did I do wrong? What should I do?

**Comment by daanbl** [comment]
That is odd. Which version of laspy are you using?

**Comment by Roy2xc** [comment]
> That is odd. Which version of laspy are you using?

Requirement already satisfied: laspy in /home/pupa/anaconda3/lib/python3.8/site-packages (2.0.2)
Requirement already satisfied: numpy in /home/pupa/anaconda3/lib/python3.8/site-packages (from laspy) (1.20.2)

**Comment by Roy2xc** [comment]
> > That is odd. Which version of laspy are you using?
> 
> Requirement already satisfied: laspy in /home/pupa/anaconda3/lib/python3.8/site-packages (2.0.2) Requirement already satisfied: numpy in /home/pupa/anaconda3/lib/python3.8/site-packages (from laspy) (1.20.2)

It is an environment problem, my environment was mess, so I built a new conda env and restart the kernel, then it works.
