### ISSUE TITLE
AttributeError: module 'pycc' has no attribute 'PointCoordinateType'

### ISSUE THREAD

**Issue by Roy2xc** [Amsterdam-AI-Team/Urban_PointCloud_Processing#39]
I just fixed the "laspy" issues but know when I run the block "pipeline.process_file(in_file, out_file)" block again, it shows me

AttributeError: module 'pycc' has no attribute 'PointCoordinateType' 

My pycc version is 2.0.0 

What should I do? Please help me~ Thank you!!

**Comment by daanbl** [comment]
You need `pycc` from this source: https://github.com/tmontaigu/CloudCompare-PythonPlugin/blob/master/docs/building.rst. There is an unfortunate name clash with [another pycc](https://pypi.org/project/pycc/), which might be causing your issue.

How did you resolve your laspy issue? If someone else runs into the same problem it might be good for them to know the solution. Feel free to comment on [your previous issue](https://github.com/Amsterdam-AI-Team/Urban_PointCloud_Processing/issues/38) and close it.

**Comment by Roy2xc** [comment]
> You need `pycc` from this source: https://github.com/tmontaigu/CloudCompare-PythonPlugin/blob/master/docs/building.rst. There is an unfortunate name clash with [another pycc](https://pypi.org/project/pycc/), which might be causing your issue.
> 
> How did you resolve your laspy issue? If someone else runs into the same problem it might be good for them to know the solution. Feel free to comment on [your previous issue](https://github.com/Amsterdam-AI-Team/Urban_PointCloud_Processing/issues/38) and close it.

I messed up my environment, so the laspy didn't work... So, I use anaconda, and restart kernel, then it works.
