### ISSUE TITLE
About Datasets

### ISSUE THREAD

**Issue by Roy2xc** [Amsterdam-AI-Team/Urban_PointCloud_Processing#40]
How can I get a BGT-like datasets of my own country? I'm using OpenStreetMap but I don't know how to get the polygon data like the BGT data.

**Comment by daanbl** [comment]
Very good question. You can look for topographic data sources and cadastral maps, if available. Online discussion boards dedicated to geo informatics might be of help too.

It would be great if we can compile a list of international resources, so if you find anything for your country please share :)
