### ISSUE TITLE
Kernel die when running pipeline

### ISSUE THREAD

**Issue by Roy2xc** [Amsterdam-AI-Team/Urban_PointCloud_Processing#41]
The log is :
INFO - Processing file ../datasets/pointcloud/filtered_2386_9702.laz.
INFO - Caching ground_surface for tile 2386_9702.
INFO - AHN [npz/ground] fuser (label=1, Ground).
INFO - Processor finished in 0.02s, 0 points labelled.
INFO - Noise filter (label=99, Noise).

What are the possible problems? Can you give me some tips so that I can debug?

**Comment by daanbl** [comment]
You can enable all log messages by setting `log_utils.add_console_logger(logging.DEBUG)` in the second cell of the notebook. Does that give more info?

**Comment by Roy2xc** [comment]
> You can enable all log messages by setting `log_utils.add_console_logger(logging.DEBUG)` in the second cell of the notebook. Does that give more info?

Yes, That's help a lot. I'm trying to debug, thank you very much!

**Comment by Roy2xc** [comment]
But it just show me some DEBUG - Caching enabled in the log file, then crash.
