### ISSUE TITLE
Bug in 'refine_ground' causes AHNFuser to incorrectly miss parts of the ground points.

### ISSUE THREAD

**Issue by daanbl** [Amsterdam-AI-Team/Urban_PointCloud_Processing#50]
There is a bug in the AHNFuser for ground that sometimes causes large parts of ground to be unlabelled.

If you notice this happening, for now it can be prevented by disabling ground refinement, e.g.
`npz_ground_fuser = fusion.AHNFuser(Labels.GROUND, ahn_reader, target='ground', epsilon=0.2, refine_ground=False)`

**Comment by SimonBXY** [comment]
> There is a bug in the AHNFuser for ground that sometimes causes large parts of ground to be unlabelled.
> 
> If you notice this happening, for now it can be prevented by disabling ground refinement, e.g. `npz_ground_fuser = fusion.AHNFuser(Labels.GROUND, ahn_reader, target='ground', epsilon=0.2, refine_ground=False)`

Hello, I tried to reproduce the code in the original text again. After reading your comment, you have successfully run the code, right?
