### ISSUE TITLE
AttributeError: module 'pycc' has no attribute 'PointCoordinateType'

### ISSUE THREAD

**Issue by Ameliecc** [Amsterdam-AI-Team/Urban_PointCloud_Processing#64]
![1685357337064](https://github.com/Amsterdam-AI-Team/Urban_PointCloud_Processing/assets/88390612/e1086854-a127-41ab-a271-48e13b40ac9c)

**Comment by chrise96** [comment]
How did you install the Python package? Was it through PyPi or via https://github.com/tmontaigu/CloudCompare-PythonPlugin?

**Comment by RoychenHKMU** [comment]
i use anaconda to create a environment, then Clone the repository and Install the dependencies, after that i install Jupyter Notebook and lunch it, it pop up a browser, after that i run the "0. Complete solution.ipynb" notebook, it show a error missing "Pycc" so i install it by using "pip install pycc" in the environment.

when i run "pipeline.process_file(in_file, out_file)" it show "AttributeError: module 'pycc' has no attribute 'PointCoordinateType'". please someone help, thank you so much.

**Comment by daanbl** [comment]
You need to install `pycc` from source, see [step 3 in our installation instructions](https://github.com/Amsterdam-AI-Team/Urban_PointCloud_Processing#installation). There is an unfortunate name clash with a standard pip package, that's why `pip install pycc` does not work.

**Comment by RoychenHKMU** [comment]
I am not sure how to install pycc and how to use Qt. This is my workflow. Can you please help me check? thank you so much!!

window 11 system
1, i create a environment in anaconda, python 3.9
2, git clone https://github.com/Amsterdam-AI-Team/Urban_PointCloud_Processing.git
3, cd Urban_PointCloud_Processing & python -m pip install -r requirements.txt
4, download the CloudCompare-PythonPlugin project, and put it in Urban_PointCloud project file, then cd CloudCompare-PythonPlugin-master.
5, pip install wrapper/cccorelib (Successfully installed cccorelib-0.0.1)
6, pip install wrapper/pycc (Error,  ERROR: Failed building wheel for pycc, ERROR: Could not build wheels for pycc, which is required to install pyproject.toml-based projects )

**Comment by daanbl** [comment]
Unfortunately I am aware that it can be more difficult to get that package working on Windows. Since pycc is developed by others, it is best to ask for help in that repository directly: https://github.com/tmontaigu/CloudCompare-PythonPlugin/issues
