### ISSUE TITLE
How to segment the road pointcloud?

### ISSUE THREAD

**Issue by dux915hhh** [Amsterdam-AI-Team/Urban_PointCloud_Processing#66]
HI, teacher, I am a beginner of python and segmentation. I was wondering how did you define a road using elevation, like region growing? Here is the function I was confused: 'fusion.BGTRoadFuser(Labels.ROAD, bgt_reader=bgt_road_reader)'.

Thank you so much!

**Comment by daanbl** [comment]
Hi! To segment the road we use a combination of elevation and topographical data. There are two steps:

1. Segment all ground points using elevation data;
2. Segment road from the ground points of step 1, using topographical maps.

Hope this helps.

**Comment by dux915hhh** [comment]
Thank you so much for replying soon.  Is topographical maps already defined where is the sidewalk, where is the pavement? If I don't have topographical information, could I still extract only sidewalk or pavement? Thanks in advance!

**Comment by daanbl** [comment]
In our case the topographical map already included this information. If you don't have that data, you'll need other methods. Depending on the resolution of the point cloud you might be able to do some form of edge detection to find curb ramps.

Another possibility is to generate the topographical map from aerial images, for example using this project: https://github.com/VIDA-NYU/tile2net

**Comment by dux915hhh** [comment]
That is really helpful to me, I will try to generate topographical map first. Thank you.
