### ISSUE TITLE
BGT demo files

### ISSUE THREAD

**Issue by ChemicalNRG** [Amsterdam-AI-Team/Urban_PointCloud_Processing#67]
The BGT demo files are in .csv and I think only Amsterdam has them in csv downloadable.

Is it possible to change the script(s) to include .gml for the rest of the country? 
Or maybe a conversion script for gml to csv, or a link to download csv's for other city's?

Thanks

**Comment by ChemicalNRG** [comment]
seeing issue/enhancement #59 it is maybe better to get things working with gml, gpkg or psql instead of csv?

**Comment by daanbl** [comment]
@ChemicalNRG thank you for your suggestion, indeed that would be a nice improvement. Unfortunately this repository is currently not actively maintained, and this change would require a large overhaul of the codebase that I currently don't have time for.

For now, extracting the required fields from GML should be relatively straightforward. Our current implementation actually converts from GeoJSON, see https://github.com/Amsterdam-AI-Team/Urban_PointCloud_Processing/blob/main/src/upcp/scrapers/ams_bgt_scraper.py, so you could write a GML scraper in similar fashion.
